//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineTest1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    using System.Web.Mvc;

    public partial class EmployeeTbl
    {
        public int EmpId { get; set; }

        [Display(Name = "First Name")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        public string LastName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return string.Format("{0} {1}", FirstName, LastName); }
        }

        [Required]
        public string Gender { get; set; }

        [Display(Name = "Date of Birth")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime DOB { get; set; }

        [Required]
        public int Age { get; set; }

        public bool IsMarathi { get; set; }

        public bool IsHindi { get; set; }

        public bool IsEnglish { get; set; }

        public string Languages 
        { 
            get { return Main(); }
        }

        public string Main()
        {

            StringBuilder languages = new StringBuilder();
            if (IsMarathi)
            {
                languages.Append("Marathi");
                languages.Append(" | ");
            }
            if (IsHindi)
            {
                languages.Append("Hindi");
                languages.Append(" | ");
            }
            if (IsEnglish)
            {
                languages.Append("English");
                languages.Append(" | ");
            }
            string newlanguages = languages.ToString();
            newlanguages = newlanguages.Remove(newlanguages.Length - 2);
            return newlanguages;
        }

        public Nullable<int> CountryId { get; set; }

        public SelectList CountryList { get; set; }

        public virtual CountryTbl CountryTbl { get; set; }
    }
}
